auditbeat.modules:

#- module: auditd
#  audit_rules: |
#    -w /etc/passwd -p wa -k identity
#    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access



#- module: auditd
#  audit_rules: |
#    # Monitor shell executions
#    -a always,exit -F arch=b64 -S execve -k shell_exec
#    -a always,exit -F arch=b32 -S execve -k shell_exec


- module: file_integrity
  paths:
     - '${AUDITBEAT_WATCHDIR}/app'
  recursive: false

  processors:
    - add_cloud_metadata: ~
    - add_id:
        target_field: alert_id
    - add_fields:
        target: ''
        fields:
          charging_point_id: '${CHARGING_STATION_ID}'

#output.http:
  # Your HTTP endpoint
#  hosts: ["http://192.168.0.12:5556"]

#output.console:
#  pretty: true

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'


output.elasticsearch:
  hosts: ["http://${CENTRAL_MANAGEMENT_SERVER_HOST}:9200"]
  username: "elastic"  # Optional: Add if you have authentication enabled
  password: "password" # Optional: Add if you have authentication enabled
