version: "3.8"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - "9000:9000"
      - "5556:5556"
    env_file:
      - ./.env
    network_mode: "host"

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./server/initdb:/docker-entrypoint-initdb.d
      - ./serverdata:/var/lib/postgresql/data

    env_file:
      - ./.env
    network_mode: "host"
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

    network_mode: "host"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    network_mode: "host"
    environment:
      - xpack.monitoring.enabled=false
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
