version: "3.8"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    env_file:
      - ./.env
    network_mode: "host"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - "80:80"
    env_file:
      - ./.env
    network_mode: "host"

  hw-manager:
    build:
      context: ./hw-manager
      dockerfile: Dockerfile

    ports:
      - "5001:5001"

    env_file:
      - ./.env

    privileged: true
    security_opt:
      - apparmor:unconfined
    pid: "host"
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    network_mode: "host"


  auditbeat:
    image: docker.elastic.co/beats/auditbeat:8.5.0 # Use the appropriate version
    container_name: auditbeat
    privileged: true # Required for Auditbeat to monitor the host
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - /dev:/host/dev
      - /var/lib/docker:/var/lib/docker:ro
      - ./auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml
    cap_add:
      - AUDIT_CONTROL  # Add capabilities
      - AUDIT_READ
    pid: host

    env_file:
      - ./.env
    environment:
      - AUDITBEAT_WATCHDIR=${AUDITBEAT_WATCHDIR}
    command: >
      -e
      --strict.perms=false

    network_mode: "host"

    depends_on:
      - hw-manager
