version: "3.8"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    env_file:
      - ./.env
    network_mode: "host"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - "80:80"
    env_file:
      - ./.env
    network_mode: "host"

  hw-manager:
    build:
      context: ./hw-manager
      dockerfile: Dockerfile

    ports:
      - "5001:5001"

    env_file:
      - ./.env

    privileged: true
    security_opt:
      - apparmor:unconfined
    pid: "host"
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    network_mode: "host"